package org.assertj.examples.rpg;

/**
 * Abstract base class for {@link Wand} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractWandAssert<S extends AbstractWandAssert<S, A>, A extends Wand> extends AbstractItemAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractWandAssert}</code> to make assertions on actual Wand.
   * @param actual the Wand we want to make assertions on.
   */
  protected AbstractWandAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
