package org.assertj.examples.rpg;

/**
 * {@link Item} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractItemAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class ItemAssert extends AbstractItemAssert<ItemAssert, Item> {

  /**
   * Creates a new <code>{@link ItemAssert}</code> to make assertions on actual Item.
   * @param actual the Item we want to make assertions on.
   */
  public ItemAssert(Item actual) {
    super(actual, ItemAssert.class);
  }

  /**
   * An entry point for ItemAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myItem)</code> and get specific assertion with code completion.
   * @param actual the Item we want to make assertions on.
   * @return a new <code>{@link ItemAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static ItemAssert assertThat(Item actual) {
    return new ItemAssert(actual);
  }
}
