package org.assertj.examples.rpg;


/**
 * {@link Item} specific assertions - Generated by me.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractItemAssert} instead.
 */
public class ItemAssert extends AbstractItemAssert<ItemAssert, Item> {

  /**
   * Creates a new <code>{@link ItemAssert}</code> to make assertions on actual Item.
   * @param actual the Item we want to make assertions on.
   */
  public ItemAssert(Item actual) {
    super(actual, ItemAssert.class);
  }

  /**
   * factory method for Item assertions.
   * @return a new <code>{@link ItemAssert}</code>
   */
  public static ItemAssert assertThat(Item actual) {
    return new ItemAssert(actual);
  }
}
