package org.assertj.examples.rpg;


/**
 * {@link Wand} specific assertions - Generated by me.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractWandAssert} instead.
 */
public class WandAssert extends AbstractWandAssert<WandAssert, Wand> {

  /**
   * Creates a new <code>{@link WandAssert}</code> to make assertions on actual Wand.
   * @param actual the Wand we want to make assertions on.
   */
  public WandAssert(Wand actual) {
    super(actual, WandAssert.class);
  }

  /**
   * factory method for Wand assertions.
   * @return a new <code>{@link WandAssert}</code>
   */
  public static WandAssert assertThat(Wand actual) {
    return new WandAssert(actual);
  }
}
