package org.assertj.examples.data.bug18;


/**
 * {@link Dollar$} specific assertions - Generated by me.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractDollar$Assert} instead.
 */
public class Dollar$Assert extends AbstractDollar$Assert<Dollar$Assert, Dollar$> {

  /**
   * Creates a new <code>{@link Dollar$Assert}</code> to make assertions on actual Dollar$.
   * @param actual the Dollar$ we want to make assertions on.
   */
  public Dollar$Assert(Dollar$ actual) {
    super(actual, Dollar$Assert.class);
  }

  /**
   * factory method for Dollar$ assertions.
   * @return a new <code>{@link Dollar$Assert}</code>
   */
  public static Dollar$Assert assertThat(Dollar$ actual) {
    return new Dollar$Assert(actual);
  }
}
