package org.assertj.examples.data.neo4j;

import org.assertj.core.api.AbstractObjectAssert;
import org.assertj.core.util.Objects;

/**
 * Abstract base class for {@link DragonBallGraphRepository} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractDragonBallGraphRepositoryAssert<S extends AbstractDragonBallGraphRepositoryAssert<S, A>, A extends DragonBallGraphRepository> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractDragonBallGraphRepositoryAssert}</code> to make assertions on actual DragonBallGraphRepository.
   * @param actual the DragonBallGraphRepository we want to make assertions on.
   */
  protected AbstractDragonBallGraphRepositoryAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

  /**
   * Verifies that the actual DragonBallGraphRepository's graphDatabase is equal to the given one.
   * @param graphDatabase the given graphDatabase to compare the actual DragonBallGraphRepository's graphDatabase to.
   * @return this assertion object.
   * @throws AssertionError - if the actual DragonBallGraphRepository's graphDatabase is not equal to the given one.
   */
  public S hasGraphDatabase(org.neo4j.graphdb.GraphDatabaseService graphDatabase) {
    // check that actual DragonBallGraphRepository we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting graphDatabase of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    org.neo4j.graphdb.GraphDatabaseService actualGraphDatabase = org.assertj.core.util.introspection.FieldSupport.EXTRACTION.fieldValue("graphDatabase", org.neo4j.graphdb.GraphDatabaseService.class, actual);
    if (!Objects.areEqual(actualGraphDatabase, graphDatabase)) {
      failWithMessage(assertjErrorMessage, actual, graphDatabase, actualGraphDatabase);
    }

    // return the current assertion for method chaining
    return myself;
  }

}
