package org.assertj.examples.data.neo4j;

import org.assertj.core.api.AbstractObjectAssert;

/**
 * Abstract base class for {@link DragonBallGraph} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractDragonBallGraphAssert<S extends AbstractDragonBallGraphAssert<S, A>, A extends DragonBallGraph> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractDragonBallGraphAssert}</code> to make assertions on actual DragonBallGraph.
   * @param actual the DragonBallGraph we want to make assertions on.
   */
  protected AbstractDragonBallGraphAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
