package org.assertj.examples.data.neo4j;

import org.assertj.core.api.AbstractAssert;

/**
 * Abstract base class for {@link DragonBallGraphRepository} specific assertions - Generated by CustomAssertionGenerator.
 */
public abstract class AbstractDragonBallGraphRepositoryAssert<S extends AbstractDragonBallGraphRepositoryAssert<S, A>, A extends DragonBallGraphRepository> extends AbstractAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractDragonBallGraphRepositoryAssert}</code> to make assertions on actual DragonBallGraphRepository.
   * @param actual the DragonBallGraphRepository we want to make assertions on.
   */
  protected AbstractDragonBallGraphRepositoryAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
