package org.assertj.examples.data.neo4j;


/**
 * {@link DragonBallGraphRepository} specific assertions - Generated by me.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractDragonBallGraphRepositoryAssert} instead.
 */
public class DragonBallGraphRepositoryAssert extends AbstractDragonBallGraphRepositoryAssert<DragonBallGraphRepositoryAssert, DragonBallGraphRepository> {

  /**
   * Creates a new <code>{@link DragonBallGraphRepositoryAssert}</code> to make assertions on actual DragonBallGraphRepository.
   * @param actual the DragonBallGraphRepository we want to make assertions on.
   */
  public DragonBallGraphRepositoryAssert(DragonBallGraphRepository actual) {
    super(actual, DragonBallGraphRepositoryAssert.class);
  }

  /**
   * factory method for DragonBallGraphRepository assertions.
   * @return a new <code>{@link DragonBallGraphRepositoryAssert}</code>
   */
  public static DragonBallGraphRepositoryAssert assertThat(DragonBallGraphRepository actual) {
    return new DragonBallGraphRepositoryAssert(actual);
  }
}
