package org.assertj.examples.data.neo4j;


/**
 * {@link DragonBallGraph} specific assertions - Generated by me.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractDragonBallGraphAssert} instead.
 */
public class DragonBallGraphAssert extends AbstractDragonBallGraphAssert<DragonBallGraphAssert, DragonBallGraph> {

  /**
   * Creates a new <code>{@link DragonBallGraphAssert}</code> to make assertions on actual DragonBallGraph.
   * @param actual the DragonBallGraph we want to make assertions on.
   */
  public DragonBallGraphAssert(DragonBallGraph actual) {
    super(actual, DragonBallGraphAssert.class);
  }

  /**
   * factory method for DragonBallGraph assertions.
   * @return a new <code>{@link DragonBallGraphAssert}</code>
   */
  public static DragonBallGraphAssert assertThat(DragonBallGraph actual) {
    return new DragonBallGraphAssert(actual);
  }
}
