package org.assertj.examples.data.neo4j;

/**
 * {@link DragonBallGraphRepository} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractDragonBallGraphRepositoryAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class DragonBallGraphRepositoryAssert extends AbstractDragonBallGraphRepositoryAssert<DragonBallGraphRepositoryAssert, DragonBallGraphRepository> {

  /**
   * Creates a new <code>{@link DragonBallGraphRepositoryAssert}</code> to make assertions on actual DragonBallGraphRepository.
   * @param actual the DragonBallGraphRepository we want to make assertions on.
   */
  public DragonBallGraphRepositoryAssert(DragonBallGraphRepository actual) {
    super(actual, DragonBallGraphRepositoryAssert.class);
  }

  /**
   * An entry point for DragonBallGraphRepositoryAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myDragonBallGraphRepository)</code> and get specific assertion with code completion.
   * @param actual the DragonBallGraphRepository we want to make assertions on.
   * @return a new <code>{@link DragonBallGraphRepositoryAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static DragonBallGraphRepositoryAssert assertThat(DragonBallGraphRepository actual) {
    return new DragonBallGraphRepositoryAssert(actual);
  }
}
