package org.assertj.examples.data.neo4j;

/**
 * {@link DragonBallGraphRepository} specific assertions - Generated by me.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractDragonBallGraphAssert} instead.
 */
public class DragonBallGraphAssert extends AbstractDragonBallGraphAssert<DragonBallGraphAssert, DragonBallGraphRepository> {

  /**
   * Creates a new <code>{@link DragonBallGraphAssert}</code> to make assertions on actual DragonBallGraph.
   * @param actual the DragonBallGraph we want to make assertions on.
   */
  public DragonBallGraphAssert(DragonBallGraphRepository actual) {
    super(actual, DragonBallGraphAssert.class);
  }

  /**
   * factory method for DragonBallGraph assertions.
   * @return a new <code>{@link DragonBallGraphAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static DragonBallGraphAssert assertThat(DragonBallGraphRepository actual) {
    return new DragonBallGraphAssert(actual);
  }
}
