package com.google.common.net;

import org.assertj.core.api.AbstractAssert;

/**
 * Abstract base class for {@link InetAddresses} specific assertions - Generated by CustomAssertionGenerator.
 */
public abstract class AbstractInetAddressesAssert<S extends AbstractInetAddressesAssert<S, A>, A extends InetAddresses> extends AbstractAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractInetAddressesAssert}</code> to make assertions on actual InetAddresses.
   * @param actual the InetAddresses we want to make assertions on.
   */
  protected AbstractInetAddressesAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
