package com.google.common.net;

import org.assertj.core.api.AbstractAssert;

/**
 * Abstract base class for {@link InternetDomainName} specific assertions - Generated by CustomAssertionGenerator.
 */
public abstract class AbstractInternetDomainNameAssert<S extends AbstractInternetDomainNameAssert<S, A>, A extends InternetDomainName> extends AbstractAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractInternetDomainNameAssert}</code> to make assertions on actual InternetDomainName.
   * @param actual the InternetDomainName we want to make assertions on.
   */
  protected AbstractInternetDomainNameAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

  /**
   * Verifies that the actual InternetDomainName has parent.
   * @return this assertion object.
   * @throws AssertionError - if the actual InternetDomainName does not have parent.
   */
  public S hasParent() {
    // check that actual InternetDomainName we want to make assertions on is not null.
    isNotNull();

    // check
    if (!actual.hasParent()) {
      failWithMessage("\nExpecting that actual InternetDomainName has parent but does not have.");
    }
    
    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual InternetDomainName does not have parent.
   * @return this assertion object.
   * @throws AssertionError - if the actual InternetDomainName has parent.
   */
  public S doesNotHaveParent() {
    // check that actual InternetDomainName we want to make assertions on is not null.
    isNotNull();

    // check
    if (actual.hasParent()) {
      failWithMessage("\nExpecting that actual InternetDomainName does not have parent but has.");
    }
    
    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual InternetDomainName has public suffix.
   * @return this assertion object.
   * @throws AssertionError - if the actual InternetDomainName does not have public suffix.
   */
  public S hasPublicSuffix() {
    // check that actual InternetDomainName we want to make assertions on is not null.
    isNotNull();

    // check
    if (!actual.hasPublicSuffix()) {
      failWithMessage("\nExpecting that actual InternetDomainName has public suffix but does not have.");
    }
    
    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual InternetDomainName does not have public suffix.
   * @return this assertion object.
   * @throws AssertionError - if the actual InternetDomainName has public suffix.
   */
  public S doesNotHavePublicSuffix() {
    // check that actual InternetDomainName we want to make assertions on is not null.
    isNotNull();

    // check
    if (actual.hasPublicSuffix()) {
      failWithMessage("\nExpecting that actual InternetDomainName does not have public suffix but has.");
    }
    
    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual InternetDomainName is public suffix.
   * @return this assertion object.
   * @throws AssertionError - if the actual InternetDomainName is not public suffix.
   */
  public S isPublicSuffix() {
    // check that actual InternetDomainName we want to make assertions on is not null.
    isNotNull();

    // check
    if (!actual.isPublicSuffix()) {
      failWithMessage("\nExpecting that actual InternetDomainName is public suffix but is not.");
    }
    
    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual InternetDomainName is not public suffix.
   * @return this assertion object.
   * @throws AssertionError - if the actual InternetDomainName is public suffix.
   */
  public S isNotPublicSuffix() {
    // check that actual InternetDomainName we want to make assertions on is not null.
    isNotNull();

    // check
    if (actual.isPublicSuffix()) {
      failWithMessage("\nExpecting that actual InternetDomainName is not public suffix but is.");
    }
    
    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual InternetDomainName is top private domain.
   * @return this assertion object.
   * @throws AssertionError - if the actual InternetDomainName is not top private domain.
   */
  public S isTopPrivateDomain() {
    // check that actual InternetDomainName we want to make assertions on is not null.
    isNotNull();

    // check
    if (!actual.isTopPrivateDomain()) {
      failWithMessage("\nExpecting that actual InternetDomainName is top private domain but is not.");
    }
    
    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual InternetDomainName is not top private domain.
   * @return this assertion object.
   * @throws AssertionError - if the actual InternetDomainName is top private domain.
   */
  public S isNotTopPrivateDomain() {
    // check that actual InternetDomainName we want to make assertions on is not null.
    isNotNull();

    // check
    if (actual.isTopPrivateDomain()) {
      failWithMessage("\nExpecting that actual InternetDomainName is not top private domain but is.");
    }
    
    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual InternetDomainName is under public suffix.
   * @return this assertion object.
   * @throws AssertionError - if the actual InternetDomainName is not under public suffix.
   */
  public S isUnderPublicSuffix() {
    // check that actual InternetDomainName we want to make assertions on is not null.
    isNotNull();

    // check
    if (!actual.isUnderPublicSuffix()) {
      failWithMessage("\nExpecting that actual InternetDomainName is under public suffix but is not.");
    }
    
    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual InternetDomainName is not under public suffix.
   * @return this assertion object.
   * @throws AssertionError - if the actual InternetDomainName is under public suffix.
   */
  public S isNotUnderPublicSuffix() {
    // check that actual InternetDomainName we want to make assertions on is not null.
    isNotNull();

    // check
    if (actual.isUnderPublicSuffix()) {
      failWithMessage("\nExpecting that actual InternetDomainName is not under public suffix but is.");
    }
    
    // return the current assertion for method chaining
    return myself;
  }

}
