package com.google.common.net;


/**
 * {@link InetAddresses} specific assertions - Generated by me.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractInetAddressesAssert} instead.
 */
public class InetAddressesAssert extends AbstractInetAddressesAssert<InetAddressesAssert, InetAddresses> {

  /**
   * Creates a new <code>{@link InetAddressesAssert}</code> to make assertions on actual InetAddresses.
   * @param actual the InetAddresses we want to make assertions on.
   */
  public InetAddressesAssert(InetAddresses actual) {
    super(actual, InetAddressesAssert.class);
  }

  /**
   * factory method for InetAddresses assertions.
   * @return a new <code>{@link InetAddressesAssert}</code>
   */
  public static InetAddressesAssert assertThat(InetAddresses actual) {
    return new InetAddressesAssert(actual);
  }
}
