package com.google.common.net;


/**
 * {@link InternetDomainName} specific assertions - Generated by me.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractInternetDomainNameAssert} instead.
 */
public class InternetDomainNameAssert extends AbstractInternetDomainNameAssert<InternetDomainNameAssert, InternetDomainName> {

  /**
   * Creates a new <code>{@link InternetDomainNameAssert}</code> to make assertions on actual InternetDomainName.
   * @param actual the InternetDomainName we want to make assertions on.
   */
  public InternetDomainNameAssert(InternetDomainName actual) {
    super(actual, InternetDomainNameAssert.class);
  }

  /**
   * factory method for InternetDomainName assertions.
   * @return a new <code>{@link InternetDomainNameAssert}</code>
   */
  public static InternetDomainNameAssert assertThat(InternetDomainName actual) {
    return new InternetDomainNameAssert(actual);
  }
}
