package com.google.common.net;

/**
 * {@link InternetDomainName} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractInternetDomainNameAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class InternetDomainNameAssert extends AbstractInternetDomainNameAssert<InternetDomainNameAssert, InternetDomainName> {

  /**
   * Creates a new <code>{@link InternetDomainNameAssert}</code> to make assertions on actual InternetDomainName.
   * @param actual the InternetDomainName we want to make assertions on.
   */
  public InternetDomainNameAssert(InternetDomainName actual) {
    super(actual, InternetDomainNameAssert.class);
  }

  /**
   * An entry point for InternetDomainNameAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myInternetDomainName)</code> and get specific assertion with code completion.
   * @param actual the InternetDomainName we want to make assertions on.
   * @return a new <code>{@link InternetDomainNameAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static InternetDomainNameAssert assertThat(InternetDomainName actual) {
    return new InternetDomainNameAssert(actual);
  }
}
