package org.assertj.examples.data.movie;

import java.util.Date;
import org.assertj.core.api.AbstractAssert;


/**
 * Abstract base class for {@link Movie} specific assertions - Generated by CustomAssertionGenerator.
 */
public abstract class AbstractMovieAssert<S extends AbstractMovieAssert<S, A>, A extends Movie> extends AbstractAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractMovieAssert}</code> to make assertions on actual Movie.
   * @param actual the Movie we want to make assertions on.
   */
  protected AbstractMovieAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

  /**
   * Verifies that the actual Movie's releaseDate is equal to the given one.
   * @param releaseDate the given releaseDate to compare the actual Movie's releaseDate to.
   * @return this assertion object.
   * @throws AssertionError - if the actual Movie's releaseDate is not equal to the given one.
   */
  public S hasReleaseDate(Date releaseDate) {
    // check that actual Movie we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpected releaseDate of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    Date actualReleaseDate = actual.getReleaseDate();
    if (!org.assertj.core.util.Objects.areEqual(actualReleaseDate, releaseDate)) {
      failWithMessage(assertjErrorMessage, actual, releaseDate, actualReleaseDate);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual Movie's title is equal to the given one.
   * @param title the given title to compare the actual Movie's title to.
   * @return this assertion object.
   * @throws AssertionError - if the actual Movie's title is not equal to the given one.
   */
  public S hasTitle(String title) {
    // check that actual Movie we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpected title of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualTitle = actual.getTitle();
    if (!org.assertj.core.util.Objects.areEqual(actualTitle, title)) {
      failWithMessage(assertjErrorMessage, actual, title, actualTitle);
    }

    // return the current assertion for method chaining
    return myself;
  }

}
