package org.assertj.examples.data.movie;

import org.assertj.core.api.AbstractAssert;
import org.assertj.core.internal.Iterables;

/**
 * Abstract base class for {@link Team} specific assertions - Generated by CustomAssertionGenerator.
 */
public abstract class AbstractTeamAssert<S extends AbstractTeamAssert<S, A>, A extends Team> extends AbstractAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractTeamAssert}</code> to make assertions on actual Team.
   * @param actual the Team we want to make assertions on.
   */
  protected AbstractTeamAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

  /**
   * Verifies that the actual Team's actors contains the given String elements.
   * @param actors the given elements that should be contained in actual Team's actors.
   * @return this assertion object.
   * @throws AssertionError if the actual Team's actors does not contain all given String elements.
   */
  public S hasActors(String... actors) {
    // check that actual Team we want to make assertions on is not null.
    isNotNull();

    // check that given String varargs is not null.
    if (actors == null) throw new AssertionError("Expecting actors parameter not to be null.");
    
    // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
    Iterables.instance().assertContains(info, actual.getActors(), actors);

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual Team has no actors.
   * @return this assertion object.
   * @throws AssertionError if the actual Team's actors is not empty.
   */
  public S hasNoActors() {
    // check that actual Team we want to make assertions on is not null.
    isNotNull();

    // we override the default error message with a more explicit one
    String assertjErrorMessage = "\nExpected :\n  <%s>\nnot to have actors but had :\n  <%s>";
    
    // check
    if (actual.getActors().iterator().hasNext()) {
      failWithMessage(assertjErrorMessage, actual, actual.getActors());
    }
    
    // return the current assertion for method chaining
    return myself;
  }
  

}
