package org.assertj.examples.data.movie;

/**
 * {@link Movie} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractMovieAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class MovieAssert extends AbstractMovieAssert<MovieAssert, Movie> {

  /**
   * Creates a new <code>{@link MovieAssert}</code> to make assertions on actual Movie.
   * @param actual the Movie we want to make assertions on.
   */
  public MovieAssert(Movie actual) {
    super(actual, MovieAssert.class);
  }

  /**
   * An entry point for MovieAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myMovie)</code> and get specific assertion with code completion.
   * @param actual the Movie we want to make assertions on.
   * @return a new <code>{@link MovieAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static MovieAssert assertThat(Movie actual) {
    return new MovieAssert(actual);
  }
}
