package org.assertj.examples.data.movie;


/**
 * {@link Movie} specific assertions - Generated by me.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractMovieAssert} instead.
 */
public class MovieAssert extends AbstractMovieAssert<MovieAssert, Movie> {

  /**
   * Creates a new <code>{@link MovieAssert}</code> to make assertions on actual Movie.
   * @param actual the Movie we want to make assertions on.
   */
  public MovieAssert(Movie actual) {
    super(actual, MovieAssert.class);
  }

  /**
   * factory method for Movie assertions.
   * @return a new <code>{@link MovieAssert}</code>
   */
  public static MovieAssert assertThat(Movie actual) {
    return new MovieAssert(actual);
  }
}
