package org.assertj.examples.data.bug27;

import org.assertj.core.api.AbstractObjectAssert;

/**
 * Abstract base class for {@link MyModelClass.MyBean} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractMyModelClassMyBeanAssert<S extends AbstractMyModelClassMyBeanAssert<S, A>, A extends MyModelClass.MyBean> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractMyModelClassMyBeanAssert}</code> to make assertions on actual MyModelClass.MyBean.
   * @param actual the MyModelClass.MyBean we want to make assertions on.
   */
  protected AbstractMyModelClassMyBeanAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
