package org.assertj.examples.data.bug27;

import org.assertj.core.api.AbstractAssert;

/**
 * Abstract base class for {@link MyModelClass} specific assertions - Generated by CustomAssertionGenerator.
 */
public abstract class AbstractMyModelClassAssert<S extends AbstractMyModelClassAssert<S, A>, A extends MyModelClass> extends AbstractAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractMyModelClassAssert}</code> to make assertions on actual MyModelClass.
   * @param actual the MyModelClass we want to make assertions on.
   */
  protected AbstractMyModelClassAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
