package org.assertj.examples.data.bug27;

import org.assertj.core.api.AbstractAssert;

/**
 * Abstract base class for {@link MyIteratorWrapper} specific assertions - Generated by CustomAssertionGenerator.
 */
public abstract class AbstractMyIteratorWrapperAssert<S extends AbstractMyIteratorWrapperAssert<S, A>, A extends MyIteratorWrapper> extends AbstractAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractMyIteratorWrapperAssert}</code> to make assertions on actual MyIteratorWrapper.
   * @param actual the MyIteratorWrapper we want to make assertions on.
   */
  protected AbstractMyIteratorWrapperAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
