package org.assertj.examples.data.bug27;


/**
 * {@link MyIteratorWrapper} specific assertions - Generated by me.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractMyIteratorWrapperAssert} instead.
 */
public class MyIteratorWrapperAssert extends AbstractMyIteratorWrapperAssert<MyIteratorWrapperAssert, MyIteratorWrapper> {

  /**
   * Creates a new <code>{@link MyIteratorWrapperAssert}</code> to make assertions on actual MyIteratorWrapper.
   * @param actual the MyIteratorWrapper we want to make assertions on.
   */
  public MyIteratorWrapperAssert(MyIteratorWrapper actual) {
    super(actual, MyIteratorWrapperAssert.class);
  }

  /**
   * factory method for MyIteratorWrapper assertions.
   * @return a new <code>{@link MyIteratorWrapperAssert}</code>
   */
  public static MyIteratorWrapperAssert assertThat(MyIteratorWrapper actual) {
    return new MyIteratorWrapperAssert(actual);
  }
}
