package org.assertj.examples.data.bug27;


/**
 * {@link MyModelClass.MyBean} specific assertions - Generated by me.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractMyModelClassMyBeanAssert} instead.
 */
public class MyModelClassMyBeanAssert extends AbstractMyModelClassMyBeanAssert<MyModelClassMyBeanAssert, MyModelClass.MyBean> {

  /**
   * Creates a new <code>{@link MyModelClassMyBeanAssert}</code> to make assertions on actual MyModelClass.MyBean.
   * @param actual the MyModelClass.MyBean we want to make assertions on.
   */
  public MyModelClassMyBeanAssert(MyModelClass.MyBean actual) {
    super(actual, MyModelClassMyBeanAssert.class);
  }

  /**
   * factory method for MyModelClass.MyBean assertions.
   * @return a new <code>{@link MyModelClassMyBeanAssert}</code>
   */
  public static MyModelClassMyBeanAssert assertThat(MyModelClass.MyBean actual) {
    return new MyModelClassMyBeanAssert(actual);
  }
}
