package org.apache.commons.lang3.exception;


/**
 * {@link ContextedRuntimeException} specific assertions - Generated by me.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractContextedRuntimeExceptionAssert} instead.
 */
public class ContextedRuntimeExceptionAssert extends AbstractContextedRuntimeExceptionAssert<ContextedRuntimeExceptionAssert, ContextedRuntimeException> {

  /**
   * Creates a new <code>{@link ContextedRuntimeExceptionAssert}</code> to make assertions on actual ContextedRuntimeException.
   * @param actual the ContextedRuntimeException we want to make assertions on.
   */
  public ContextedRuntimeExceptionAssert(ContextedRuntimeException actual) {
    super(actual, ContextedRuntimeExceptionAssert.class);
  }

  /**
   * factory method for ContextedRuntimeException assertions.
   * @return a new <code>{@link ContextedRuntimeExceptionAssert}</code>
   */
  public static ContextedRuntimeExceptionAssert assertThat(ContextedRuntimeException actual) {
    return new ContextedRuntimeExceptionAssert(actual);
  }
}
