package org.assertj.examples.data;

import org.assertj.core.api.AbstractAssert;
import org.assertj.core.internal.Iterables;

/**
 * Abstract base class for {@link Team} specific assertions - Generated by CustomAssertionGenerator.
 */
public abstract class AbstractTeamAssert<S extends AbstractTeamAssert<S, A>, A extends Team> extends AbstractAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractTeamAssert}</code> to make assertions on actual Team.
   * @param actual the Team we want to make assertions on.
   */
  protected AbstractTeamAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

  /**
   * Verifies that the actual Team's players contains the given BasketBallPlayer elements.
   * @param players the given elements that should be contained in actual Team's players.
   * @return this assertion object.
   * @throws AssertionError if the actual Team's players does not contain all given BasketBallPlayer elements.
   */
  public S hasPlayers(BasketBallPlayer... players) {
    // check that actual Team we want to make assertions on is not null.
    isNotNull();

    // check that given BasketBallPlayer varargs is not null.
    if (players == null) throw new AssertionError("Expecting players parameter not to be null.");
    
    // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
    Iterables.instance().assertContains(info, actual.getPlayers(), players);

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual Team has no players.
   * @return this assertion object.
   * @throws AssertionError if the actual Team's players is not empty.
   */
  public S hasNoPlayers() {
    // check that actual Team we want to make assertions on is not null.
    isNotNull();

    // we override the default error message with a more explicit one
    String assertjErrorMessage = "\nExpected :\n  <%s>\nnot to have players but had :\n  <%s>";
    
    // check
    if (actual.getPlayers().iterator().hasNext()) {
      failWithMessage(assertjErrorMessage, actual, actual.getPlayers());
    }
    
    // return the current assertion for method chaining
    return myself;
  }
  

}
