package org.assertj.examples.data;

import org.assertj.core.api.AbstractObjectAssert;

/**
 * Abstract base class for {@link Mansion} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractMansionAssert<S extends AbstractMansionAssert<S, A>, A extends Mansion> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractMansionAssert}</code> to make assertions on actual Mansion.
   * @param actual the Mansion we want to make assertions on.
   */
  protected AbstractMansionAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
