package org.assertj.examples.data;

import org.assertj.core.api.AbstractObjectAssert;

/**
 * Abstract base class for {@link Powerful} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractPowerfulAssert<S extends AbstractPowerfulAssert<S, A>, A extends Powerful> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractPowerfulAssert}</code> to make assertions on actual Powerful.
   * @param actual the Powerful we want to make assertions on.
   */
  protected AbstractPowerfulAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
