package org.assertj.examples.data;

import org.assertj.core.api.AbstractComparableAssert;

/**
 * Abstract base class for {@link Alignment} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractAlignmentAssert<S extends AbstractAlignmentAssert<S, A>, A extends Alignment> extends AbstractComparableAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractAlignmentAssert}</code> to make assertions on actual Alignment.
   * @param actual the Alignment we want to make assertions on.
   */
  protected AbstractAlignmentAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
