package org.assertj.examples.data;

import org.assertj.core.api.AbstractObjectAssert;

/**
 * Abstract base class for {@link Magical} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractMagicalAssert<S extends AbstractMagicalAssert<S, A>, A extends Magical> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractMagicalAssert}</code> to make assertions on actual Magical.
   * @param actual the Magical we want to make assertions on.
   */
  protected AbstractMagicalAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
