package org.assertj.examples.data;

import org.assertj.core.api.AbstractComparableAssert;

/**
 * Abstract base class for {@link Ring} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractRingAssert<S extends AbstractRingAssert<S, A>, A extends Ring> extends AbstractComparableAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractRingAssert}</code> to make assertions on actual Ring.
   * @param actual the Ring we want to make assertions on.
   */
  protected AbstractRingAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
