package org.assertj.examples.data;


/**
 * {@link Alignment} specific assertions - Generated by me.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractAlignmentAssert} instead.
 */
public class AlignmentAssert extends AbstractAlignmentAssert<AlignmentAssert, Alignment> {

  /**
   * Creates a new <code>{@link AlignmentAssert}</code> to make assertions on actual Alignment.
   * @param actual the Alignment we want to make assertions on.
   */
  public AlignmentAssert(Alignment actual) {
    super(actual, AlignmentAssert.class);
  }

  /**
   * factory method for Alignment assertions.
   * @return a new <code>{@link AlignmentAssert}</code>
   */
  public static AlignmentAssert assertThat(Alignment actual) {
    return new AlignmentAssert(actual);
  }
}
