package org.assertj.examples.data;

/**
 * {@link Alignment} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractAlignmentAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class AlignmentAssert extends AbstractAlignmentAssert<AlignmentAssert, Alignment> {

  /**
   * Creates a new <code>{@link AlignmentAssert}</code> to make assertions on actual Alignment.
   * @param actual the Alignment we want to make assertions on.
   */
  public AlignmentAssert(Alignment actual) {
    super(actual, AlignmentAssert.class);
  }

  /**
   * An entry point for AlignmentAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myAlignment)</code> and get specific assertion with code completion.
   * @param actual the Alignment we want to make assertions on.
   * @return a new <code>{@link AlignmentAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static AlignmentAssert assertThat(Alignment actual) {
    return new AlignmentAssert(actual);
  }
}
