package org.assertj.examples.data;


/**
 * {@link ArtWork} specific assertions - Generated by me.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractArtWorkAssert} instead.
 */
public class ArtWorkAssert extends AbstractArtWorkAssert<ArtWorkAssert, ArtWork> {

  /**
   * Creates a new <code>{@link ArtWorkAssert}</code> to make assertions on actual ArtWork.
   * @param actual the ArtWork we want to make assertions on.
   */
  public ArtWorkAssert(ArtWork actual) {
    super(actual, ArtWorkAssert.class);
  }

  /**
   * factory method for ArtWork assertions.
   * @return a new <code>{@link ArtWorkAssert}</code>
   */
  public static ArtWorkAssert assertThat(ArtWork actual) {
    return new ArtWorkAssert(actual);
  }
}
