package org.assertj.examples.data;


/**
 * {@link Book} specific assertions - Generated by me.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractBookAssert} instead.
 */
public class BookAssert extends AbstractBookAssert<BookAssert, Book> {

  /**
   * Creates a new <code>{@link BookAssert}</code> to make assertions on actual Book.
   * @param actual the Book we want to make assertions on.
   */
  public BookAssert(Book actual) {
    super(actual, BookAssert.class);
  }

  /**
   * factory method for Book assertions.
   * @return a new <code>{@link BookAssert}</code>
   */
  public static BookAssert assertThat(Book actual) {
    return new BookAssert(actual);
  }
}
