package org.assertj.examples.data;


/**
 * {@link ClassUsingDifferentClassesWithSameName} specific assertions - Generated by me.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractClassUsingDifferentClassesWithSameNameAssert} instead.
 */
public class ClassUsingDifferentClassesWithSameNameAssert extends AbstractClassUsingDifferentClassesWithSameNameAssert<ClassUsingDifferentClassesWithSameNameAssert, ClassUsingDifferentClassesWithSameName> {

  /**
   * Creates a new <code>{@link ClassUsingDifferentClassesWithSameNameAssert}</code> to make assertions on actual ClassUsingDifferentClassesWithSameName.
   * @param actual the ClassUsingDifferentClassesWithSameName we want to make assertions on.
   */
  public ClassUsingDifferentClassesWithSameNameAssert(ClassUsingDifferentClassesWithSameName actual) {
    super(actual, ClassUsingDifferentClassesWithSameNameAssert.class);
  }

  /**
   * factory method for ClassUsingDifferentClassesWithSameName assertions.
   * @return a new <code>{@link ClassUsingDifferentClassesWithSameNameAssert}</code>
   */
  public static ClassUsingDifferentClassesWithSameNameAssert assertThat(ClassUsingDifferentClassesWithSameName actual) {
    return new ClassUsingDifferentClassesWithSameNameAssert(actual);
  }
}
