package org.assertj.examples.data;


/**
 * {@link Employee} specific assertions - Generated by me.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractEmployeeAssert} instead.
 */
public class EmployeeAssert extends AbstractEmployeeAssert<EmployeeAssert, Employee> {

  /**
   * Creates a new <code>{@link EmployeeAssert}</code> to make assertions on actual Employee.
   * @param actual the Employee we want to make assertions on.
   */
  public EmployeeAssert(Employee actual) {
    super(actual, EmployeeAssert.class);
  }

  /**
   * factory method for Employee assertions.
   * @return a new <code>{@link EmployeeAssert}</code>
   */
  public static EmployeeAssert assertThat(Employee actual) {
    return new EmployeeAssert(actual);
  }
}
