package org.assertj.examples.data;

/**
 * {@link Employee} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractEmployeeAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class EmployeeAssert extends AbstractEmployeeAssert<EmployeeAssert, Employee> {

  /**
   * Creates a new <code>{@link EmployeeAssert}</code> to make assertions on actual Employee.
   * @param actual the Employee we want to make assertions on.
   */
  public EmployeeAssert(Employee actual) {
    super(actual, EmployeeAssert.class);
  }

  /**
   * An entry point for EmployeeAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myEmployee)</code> and get specific assertion with code completion.
   * @param actual the Employee we want to make assertions on.
   * @return a new <code>{@link EmployeeAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static EmployeeAssert assertThat(Employee actual) {
    return new EmployeeAssert(actual);
  }
}
