package org.assertj.examples.data;


/**
 * {@link Employee.Title} specific assertions - Generated by me.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractEmployeeTitleAssert} instead.
 */
public class EmployeeTitleAssert extends AbstractEmployeeTitleAssert<EmployeeTitleAssert, Employee.Title> {

  /**
   * Creates a new <code>{@link EmployeeTitleAssert}</code> to make assertions on actual Employee.Title.
   * @param actual the Employee.Title we want to make assertions on.
   */
  public EmployeeTitleAssert(Employee.Title actual) {
    super(actual, EmployeeTitleAssert.class);
  }

  /**
   * factory method for Employee.Title assertions.
   * @return a new <code>{@link EmployeeTitleAssert}</code>
   */
  public static EmployeeTitleAssert assertThat(Employee.Title actual) {
    return new EmployeeTitleAssert(actual);
  }
}
