package org.assertj.examples.data;


/**
 * {@link Magical} specific assertions - Generated by me.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractMagicalAssert} instead.
 */
public class MagicalAssert extends AbstractMagicalAssert<MagicalAssert, Magical> {

  /**
   * Creates a new <code>{@link MagicalAssert}</code> to make assertions on actual Magical.
   * @param actual the Magical we want to make assertions on.
   */
  public MagicalAssert(Magical actual) {
    super(actual, MagicalAssert.class);
  }

  /**
   * factory method for Magical assertions.
   * @return a new <code>{@link MagicalAssert}</code>
   */
  public static MagicalAssert assertThat(Magical actual) {
    return new MagicalAssert(actual);
  }
}
