package org.assertj.examples.data;


/**
 * {@link Name} specific assertions - Generated by me.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractNameAssert} instead.
 */
public class NameAssert extends AbstractNameAssert<NameAssert, Name> {

  /**
   * Creates a new <code>{@link NameAssert}</code> to make assertions on actual Name.
   * @param actual the Name we want to make assertions on.
   */
  public NameAssert(Name actual) {
    super(actual, NameAssert.class);
  }

  /**
   * factory method for Name assertions.
   * @return a new <code>{@link NameAssert}</code>
   */
  public static NameAssert assertThat(Name actual) {
    return new NameAssert(actual);
  }
}
