package org.assertj.examples.data;


/**
 * {@link Name} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractNameAssert} instead.
 */
public class NameAssert extends AbstractNameAssert<NameAssert, Name> {

  /**
   * Creates a new <code>{@link NameAssert}</code> to make assertions on actual Name.
   * @param actual the Name we want to make assertions on.
   */
  public NameAssert(Name actual) {
    super(actual, NameAssert.class);
  }

  /**
   * An entry point for NameAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myName)</code> and get specific assertion with code completion.
   * @param actual the Name we want to make assertions on.
   * @return a new <code>{@link NameAssert}</code>
   */
  public static NameAssert assertThat(Name actual) {
    return new NameAssert(actual);
  }
}
