package org.assertj.examples.data;

/**
 * {@link Person} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractPersonAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class PersonAssert extends AbstractPersonAssert<PersonAssert, Person> {

  /**
   * Creates a new <code>{@link PersonAssert}</code> to make assertions on actual Person.
   * @param actual the Person we want to make assertions on.
   */
  public PersonAssert(Person actual) {
    super(actual, PersonAssert.class);
  }

  /**
   * An entry point for PersonAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myPerson)</code> and get specific assertion with code completion.
   * @param actual the Person we want to make assertions on.
   * @return a new <code>{@link PersonAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static PersonAssert assertThat(Person actual) {
    return new PersonAssert(actual);
  }
}
