package org.assertj.examples.data;


/**
 * {@link Person} specific assertions - Generated by me.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractPersonAssert} instead.
 */
public class PersonAssert extends AbstractPersonAssert<PersonAssert, Person> {

  /**
   * Creates a new <code>{@link PersonAssert}</code> to make assertions on actual Person.
   * @param actual the Person we want to make assertions on.
   */
  public PersonAssert(Person actual) {
    super(actual, PersonAssert.class);
  }

  /**
   * factory method for Person assertions.
   * @return a new <code>{@link PersonAssert}</code>
   */
  public static PersonAssert assertThat(Person actual) {
    return new PersonAssert(actual);
  }
}
