package org.assertj.examples.data;

/**
 * {@link Powerful} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractPowerfulAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class PowerfulAssert extends AbstractPowerfulAssert<PowerfulAssert, Powerful> {

  /**
   * Creates a new <code>{@link PowerfulAssert}</code> to make assertions on actual Powerful.
   * @param actual the Powerful we want to make assertions on.
   */
  public PowerfulAssert(Powerful actual) {
    super(actual, PowerfulAssert.class);
  }

  /**
   * An entry point for PowerfulAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myPowerful)</code> and get specific assertion with code completion.
   * @param actual the Powerful we want to make assertions on.
   * @return a new <code>{@link PowerfulAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static PowerfulAssert assertThat(Powerful actual) {
    return new PowerfulAssert(actual);
  }
}
