package org.assertj.examples.data;

/**
 * {@link Race} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractRaceAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class RaceAssert extends AbstractRaceAssert<RaceAssert, Race> {

  /**
   * Creates a new <code>{@link RaceAssert}</code> to make assertions on actual Race.
   * @param actual the Race we want to make assertions on.
   */
  public RaceAssert(Race actual) {
    super(actual, RaceAssert.class);
  }

  /**
   * An entry point for RaceAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myRace)</code> and get specific assertion with code completion.
   * @param actual the Race we want to make assertions on.
   * @return a new <code>{@link RaceAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static RaceAssert assertThat(Race actual) {
    return new RaceAssert(actual);
  }
}
