package org.assertj.examples.data;


/**
 * {@link Race} specific assertions - Generated by me.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractRaceAssert} instead.
 */
public class RaceAssert extends AbstractRaceAssert<RaceAssert, Race> {

  /**
   * Creates a new <code>{@link RaceAssert}</code> to make assertions on actual Race.
   * @param actual the Race we want to make assertions on.
   */
  public RaceAssert(Race actual) {
    super(actual, RaceAssert.class);
  }

  /**
   * factory method for Race assertions.
   * @return a new <code>{@link RaceAssert}</code>
   */
  public static RaceAssert assertThat(Race actual) {
    return new RaceAssert(actual);
  }
}
