package org.assertj.examples.data;

/**
 * {@link Ring} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractRingAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class RingAssert extends AbstractRingAssert<RingAssert, Ring> {

  /**
   * Creates a new <code>{@link RingAssert}</code> to make assertions on actual Ring.
   * @param actual the Ring we want to make assertions on.
   */
  public RingAssert(Ring actual) {
    super(actual, RingAssert.class);
  }

  /**
   * An entry point for RingAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myRing)</code> and get specific assertion with code completion.
   * @param actual the Ring we want to make assertions on.
   * @return a new <code>{@link RingAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static RingAssert assertThat(Ring actual) {
    return new RingAssert(actual);
  }
}
