package org.assertj.examples.data;


/**
 * {@link Ring} specific assertions - Generated by me.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractRingAssert} instead.
 */
public class RingAssert extends AbstractRingAssert<RingAssert, Ring> {

  /**
   * Creates a new <code>{@link RingAssert}</code> to make assertions on actual Ring.
   * @param actual the Ring we want to make assertions on.
   */
  public RingAssert(Ring actual) {
    super(actual, RingAssert.class);
  }

  /**
   * factory method for Ring assertions.
   * @return a new <code>{@link RingAssert}</code>
   */
  public static RingAssert assertThat(Ring actual) {
    return new RingAssert(actual);
  }
}
