package org.assertj.examples.data;


/**
 * {@link Team} specific assertions - Generated by me.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractTeamAssert} instead.
 */
public class TeamAssert extends AbstractTeamAssert<TeamAssert, Team> {

  /**
   * Creates a new <code>{@link TeamAssert}</code> to make assertions on actual Team.
   * @param actual the Team we want to make assertions on.
   */
  public TeamAssert(Team actual) {
    super(actual, TeamAssert.class);
  }

  /**
   * factory method for Team assertions.
   * @return a new <code>{@link TeamAssert}</code>
   */
  public static TeamAssert assertThat(Team actual) {
    return new TeamAssert(actual);
  }
}
