package org.assertj.examples.data;


/**
 * {@link TolkienCharacter} specific assertions - Generated by me.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractTolkienCharacterAssert} instead.
 */
public class TolkienCharacterAssert extends AbstractTolkienCharacterAssert<TolkienCharacterAssert, TolkienCharacter> {

  /**
   * Creates a new <code>{@link TolkienCharacterAssert}</code> to make assertions on actual TolkienCharacter.
   * @param actual the TolkienCharacter we want to make assertions on.
   */
  public TolkienCharacterAssert(TolkienCharacter actual) {
    super(actual, TolkienCharacterAssert.class);
  }

  /**
   * factory method for TolkienCharacter assertions.
   * @return a new <code>{@link TolkienCharacterAssert}</code>
   */
  public static TolkienCharacterAssert assertThat(TolkienCharacter actual) {
    return new TolkienCharacterAssert(actual);
  }
}
