/**
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 *
 * Copyright 2012-2013 the original author or authors.
 */
package org.assertj.examples.data;

import static java.lang.String.format;

import org.assertj.core.api.AbstractAssert;
import org.assertj.core.api.Assertions;


/**
 * {@link Alignment} specific assertions - Generated by CustomAssertionGenerator.
 */
public class AlignmentAssert extends AbstractAssert<AlignmentAssert, Alignment> {

  /**
   * Creates a new </code>{@link AlignmentAssert}</code> to make assertions on actual Alignment.
   * @param actual the Alignment we want to make assertions on.
   */
  public AlignmentAssert(Alignment actual) {
    super(actual, AlignmentAssert.class);
  }

  /**
   * An entry point for AlignmentAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one's can write directly : <code>assertThat(myAlignment)</code> and get specific assertion with code completion.
   * @param actual the Alignment we want to make assertions on.
   * @return a new </code>{@link AlignmentAssert}</code>
   */
  public static AlignmentAssert assertThat(Alignment actual) {
    return new AlignmentAssert(actual);
  }

  /**
   * Verifies that the actual Alignment's declaringClass is equal to the given one.
   * @param declaringClass the given declaringClass to compare the actual Alignment's declaringClass to.
   * @return this assertion object.
   * @throws AssertionError - if the actual Alignment's declaringClass is not equal to the given one.
   */
  public AlignmentAssert hasDeclaringClass(Class declaringClass) {
    // check that actual Alignment we want to make assertions on is not null.
    isNotNull();

    // we overrides the default error message with a more explicit one
    String errorMessage = format("\nExpected <%s> declaringClass to be:\n  <%s>\n but was:\n  <%s>", actual, declaringClass, actual.getDeclaringClass());
    
    // check
    if (!actual.getDeclaringClass().equals(declaringClass)) { throw new AssertionError(errorMessage); }

    // return the current assertion for method chaining
    return this;
  }

}
