/**
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 *
 * Copyright 2012-2013 the original author or authors.
 */
package org.assertj.examples.data;

import static java.lang.String.format;

import org.assertj.core.api.AbstractAssert;
import org.assertj.core.api.Assertions;


/**
 * {@link Name} specific assertions - Generated by CustomAssertionGenerator.
 */
public class NameAssert extends AbstractAssert<NameAssert, Name> {

  /**
   * Creates a new </code>{@link NameAssert}</code> to make assertions on actual Name.
   * @param actual the Name we want to make assertions on.
   */
  public NameAssert(Name actual) {
    super(actual, NameAssert.class);
  }

  /**
   * An entry point for NameAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one's can write directly : <code>assertThat(myName)</code> and get specific assertion with code completion.
   * @param actual the Name we want to make assertions on.
   * @return a new </code>{@link NameAssert}</code>
   */
  public static NameAssert assertThat(Name actual) {
    return new NameAssert(actual);
  }

  /**
   * Verifies that the actual Name's first is equal to the given one.
   * @param first the given first to compare the actual Name's first to.
   * @return this assertion object.
   * @throws AssertionError - if the actual Name's first is not equal to the given one.
   */
  public NameAssert hasFirst(String first) {
    // check that actual Name we want to make assertions on is not null.
    isNotNull();

    // we overrides the default error message with a more explicit one
    String errorMessage = format("\nExpected <%s> first to be:\n  <%s>\n but was:\n  <%s>", actual, first, actual.getFirst());
    
    // check
    if (!actual.getFirst().equals(first)) { throw new AssertionError(errorMessage); }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual Name's last is equal to the given one.
   * @param last the given last to compare the actual Name's last to.
   * @return this assertion object.
   * @throws AssertionError - if the actual Name's last is not equal to the given one.
   */
  public NameAssert hasLast(String last) {
    // check that actual Name we want to make assertions on is not null.
    isNotNull();

    // we overrides the default error message with a more explicit one
    String errorMessage = format("\nExpected <%s> last to be:\n  <%s>\n but was:\n  <%s>", actual, last, actual.getLast());
    
    // check
    if (!actual.getLast().equals(last)) { throw new AssertionError(errorMessage); }

    // return the current assertion for method chaining
    return this;
  }

}
