/**
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 *
 * Copyright 2012-2013 the original author or authors.
 */
package org.assertj.examples.data;

import static java.lang.String.format;

import org.assertj.core.api.AbstractAssert;
import org.assertj.core.api.Assertions;


/**
 * {@link Race} specific assertions - Generated by CustomAssertionGenerator.
 */
public class RaceAssert extends AbstractAssert<RaceAssert, Race> {

  /**
   * Creates a new </code>{@link RaceAssert}</code> to make assertions on actual Race.
   * @param actual the Race we want to make assertions on.
   */
  public RaceAssert(Race actual) {
    super(actual, RaceAssert.class);
  }

  /**
   * An entry point for RaceAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one's can write directly : <code>assertThat(myRace)</code> and get specific assertion with code completion.
   * @param actual the Race we want to make assertions on.
   * @return a new </code>{@link RaceAssert}</code>
   */
  public static RaceAssert assertThat(Race actual) {
    return new RaceAssert(actual);
  }

  /**
   * Verifies that the actual Race's declaringClass is equal to the given one.
   * @param declaringClass the given declaringClass to compare the actual Race's declaringClass to.
   * @return this assertion object.
   * @throws AssertionError - if the actual Race's declaringClass is not equal to the given one.
   */
  public RaceAssert hasDeclaringClass(Class declaringClass) {
    // check that actual Race we want to make assertions on is not null.
    isNotNull();

    // we overrides the default error message with a more explicit one
    String errorMessage = format("\nExpected <%s> declaringClass to be:\n  <%s>\n but was:\n  <%s>", actual, declaringClass, actual.getDeclaringClass());
    
    // check
    if (!actual.getDeclaringClass().equals(declaringClass)) { throw new AssertionError(errorMessage); }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual Race's evilLevel is equal to the given one.
   * @param evilLevel the given evilLevel to compare the actual Race's evilLevel to.
   * @return this assertion object.
   * @throws AssertionError - if the actual Race's evilLevel is not equal to the given one.
   */
  public RaceAssert hasEvilLevel(Alignment evilLevel) {
    // check that actual Race we want to make assertions on is not null.
    isNotNull();

    // we overrides the default error message with a more explicit one
    String errorMessage = format("\nExpected <%s> evilLevel to be:\n  <%s>\n but was:\n  <%s>", actual, evilLevel, actual.getAlignment());
    
    // check
    if (!actual.getAlignment().equals(evilLevel)) { throw new AssertionError(errorMessage); }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual Race is immortal.
   * @return this assertion object.
   * @throws AssertionError - if the actual Race is not immortal.
   */
  public RaceAssert isImmortal() {
    // check that actual Race we want to make assertions on is not null.
    isNotNull();

    // we overrides the default error message with a more explicit one
    String errorMessage = format("Expected actual Race to be immortal but was not.", actual);
    
    // check
    if (!actual.isImmortal()) throw new AssertionError(errorMessage);

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual Race is not immortal.
   * @return this assertion object.
   * @throws AssertionError - if the actual Race is immortal.
   */
  public RaceAssert isNotImmortal() {
    // check that actual Race we want to make assertions on is not null.
    isNotNull();

    // we overrides the default error message with a more explicit one
    String errorMessage = format("Expected actual Race not to be immortal but was.", actual);
    
    // check
    if (actual.isImmortal()) throw new AssertionError(errorMessage);

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual Race's name is equal to the given one.
   * @param name the given name to compare the actual Race's name to.
   * @return this assertion object.
   * @throws AssertionError - if the actual Race's name is not equal to the given one.
   */
  public RaceAssert hasName(String name) {
    // check that actual Race we want to make assertions on is not null.
    isNotNull();

    // we overrides the default error message with a more explicit one
    String errorMessage = format("\nExpected <%s> name to be:\n  <%s>\n but was:\n  <%s>", actual, name, actual.getName());
    
    // check
    if (!actual.getName().equals(name)) { throw new AssertionError(errorMessage); }

    // return the current assertion for method chaining
    return this;
  }

}
