package org.assertj.examples.data.service;

import org.assertj.core.api.AbstractObjectAssert;
import org.assertj.core.internal.Iterables;

/**
 * Abstract base class for {@link TeamManager} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractTeamManagerAssert<S extends AbstractTeamManagerAssert<S, A>, A extends TeamManager> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractTeamManagerAssert}</code> to make assertions on actual TeamManager.
   * @param actual the TeamManager we want to make assertions on.
   */
  protected AbstractTeamManagerAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

  /**
   * Verifies that the actual TeamManager's players contains the given org.assertj.examples.data.BasketBallPlayer elements.
   * @param players the given elements that should be contained in actual TeamManager's players.
   * @return this assertion object.
   * @throws AssertionError if the actual TeamManager's players does not contain all given org.assertj.examples.data.BasketBallPlayer elements.
   */
  public S hasPlayers(org.assertj.examples.data.BasketBallPlayer... players) {
    // check that actual TeamManager we want to make assertions on is not null.
    isNotNull();

    // check that given org.assertj.examples.data.BasketBallPlayer varargs is not null.
    if (players == null) failWithMessage("Expecting players parameter not to be null.");

    // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
    Iterables.instance().assertContains(info, actual.getPlayers(), players);

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual TeamManager's players contains the given org.assertj.examples.data.BasketBallPlayer elements in Collection.
   * @param players the given elements that should be contained in actual TeamManager's players.
   * @return this assertion object.
   * @throws AssertionError if the actual TeamManager's players does not contain all given org.assertj.examples.data.BasketBallPlayer elements.
   */
  public S hasPlayers(java.util.Collection<? extends org.assertj.examples.data.BasketBallPlayer> players) {
    // check that actual TeamManager we want to make assertions on is not null.
    isNotNull();

    // check that given org.assertj.examples.data.BasketBallPlayer collection is not null.
    if (players == null) {
      failWithMessage("Expecting players parameter not to be null.");
      return myself; // to fool Eclipse "Null pointer access" warning on toArray.
    }

    // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
    Iterables.instance().assertContains(info, actual.getPlayers(), players.toArray());

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual TeamManager's players contains <b>only</b> the given org.assertj.examples.data.BasketBallPlayer elements and nothing else in whatever order.
   * @param players the given elements that should be contained in actual TeamManager's players.
   * @return this assertion object.
   * @throws AssertionError if the actual TeamManager's players does not contain all given org.assertj.examples.data.BasketBallPlayer elements.
   */
  public S hasOnlyPlayers(org.assertj.examples.data.BasketBallPlayer... players) {
    // check that actual TeamManager we want to make assertions on is not null.
    isNotNull();

    // check that given org.assertj.examples.data.BasketBallPlayer varargs is not null.
    if (players == null) failWithMessage("Expecting players parameter not to be null.");

    // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
    Iterables.instance().assertContainsOnly(info, actual.getPlayers(), players);

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual TeamManager's players contains <b>only</b> the given org.assertj.examples.data.BasketBallPlayer elements in Collection and nothing else in whatever order.
   * @param players the given elements that should be contained in actual TeamManager's players.
   * @return this assertion object.
   * @throws AssertionError if the actual TeamManager's players does not contain all given org.assertj.examples.data.BasketBallPlayer elements.
   */
  public S hasOnlyPlayers(java.util.Collection<? extends org.assertj.examples.data.BasketBallPlayer> players) {
    // check that actual TeamManager we want to make assertions on is not null.
    isNotNull();

    // check that given org.assertj.examples.data.BasketBallPlayer collection is not null.
    if (players == null) {
      failWithMessage("Expecting players parameter not to be null.");
      return myself; // to fool Eclipse "Null pointer access" warning on toArray.
    }

    // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
    Iterables.instance().assertContainsOnly(info, actual.getPlayers(), players.toArray());

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual TeamManager's players does not contain the given org.assertj.examples.data.BasketBallPlayer elements.
   *
   * @param players the given elements that should not be in actual TeamManager's players.
   * @return this assertion object.
   * @throws AssertionError if the actual TeamManager's players contains any given org.assertj.examples.data.BasketBallPlayer elements.
   */
  public S doesNotHavePlayers(org.assertj.examples.data.BasketBallPlayer... players) {
    // check that actual TeamManager we want to make assertions on is not null.
    isNotNull();

    // check that given org.assertj.examples.data.BasketBallPlayer varargs is not null.
    if (players == null) failWithMessage("Expecting players parameter not to be null.");

    // check with standard error message (use overridingErrorMessage before contains to set your own message).
    Iterables.instance().assertDoesNotContain(info, actual.getPlayers(), players);

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual TeamManager's players does not contain the given org.assertj.examples.data.BasketBallPlayer elements in Collection.
   *
   * @param players the given elements that should not be in actual TeamManager's players.
   * @return this assertion object.
   * @throws AssertionError if the actual TeamManager's players contains any given org.assertj.examples.data.BasketBallPlayer elements.
   */
  public S doesNotHavePlayers(java.util.Collection<? extends org.assertj.examples.data.BasketBallPlayer> players) {
    // check that actual TeamManager we want to make assertions on is not null.
    isNotNull();

    // check that given org.assertj.examples.data.BasketBallPlayer collection is not null.
    if (players == null) {
      failWithMessage("Expecting players parameter not to be null.");
      return myself; // to fool Eclipse "Null pointer access" warning on toArray.
    }

    // check with standard error message (use overridingErrorMessage before contains to set your own message).
    Iterables.instance().assertDoesNotContain(info, actual.getPlayers(), players.toArray());

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual TeamManager has no players.
   * @return this assertion object.
   * @throws AssertionError if the actual TeamManager's players is not empty.
   */
  public S hasNoPlayers() {
    // check that actual TeamManager we want to make assertions on is not null.
    isNotNull();

    // we override the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting :\n  <%s>\nnot to have players but had :\n  <%s>";

    // check
    if (actual.getPlayers().iterator().hasNext()) {
      failWithMessage(assertjErrorMessage, actual, actual.getPlayers());
    }

    // return the current assertion for method chaining
    return myself;
  }


}
