package org.assertj.examples.data.service;

import org.assertj.core.api.AbstractAssert;

/**
 * Abstract base class for {@link GameService} specific assertions - Generated by CustomAssertionGenerator.
 */
public abstract class AbstractGameServiceAssert<S extends AbstractGameServiceAssert<S, A>, A extends GameService> extends AbstractAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractGameServiceAssert}</code> to make assertions on actual GameService.
   * @param actual the GameService we want to make assertions on.
   */
  protected AbstractGameServiceAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
