package org.assertj.examples.data.service;


/**
 * {@link GameService} specific assertions - Generated by me.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractGameServiceAssert} instead.
 */
public class GameServiceAssert extends AbstractGameServiceAssert<GameServiceAssert, GameService> {

  /**
   * Creates a new <code>{@link GameServiceAssert}</code> to make assertions on actual GameService.
   * @param actual the GameService we want to make assertions on.
   */
  public GameServiceAssert(GameService actual) {
    super(actual, GameServiceAssert.class);
  }

  /**
   * factory method for GameService assertions.
   * @return a new <code>{@link GameServiceAssert}</code>
   */
  public static GameServiceAssert assertThat(GameService actual) {
    return new GameServiceAssert(actual);
  }
}
