package org.assertj.examples.data.service;

/**
 * {@link TeamManager} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractTeamManagerAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class TeamManagerAssert extends AbstractTeamManagerAssert<TeamManagerAssert, TeamManager> {

  /**
   * Creates a new <code>{@link TeamManagerAssert}</code> to make assertions on actual TeamManager.
   * @param actual the TeamManager we want to make assertions on.
   */
  public TeamManagerAssert(TeamManager actual) {
    super(actual, TeamManagerAssert.class);
  }

  /**
   * An entry point for TeamManagerAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myTeamManager)</code> and get specific assertion with code completion.
   * @param actual the TeamManager we want to make assertions on.
   * @return a new <code>{@link TeamManagerAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static TeamManagerAssert assertThat(TeamManager actual) {
    return new TeamManagerAssert(actual);
  }
}
