package org.assertj.examples.data.service;


/**
 * {@link TeamManager} specific assertions - Generated by me.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractTeamManagerAssert} instead.
 */
public class TeamManagerAssert extends AbstractTeamManagerAssert<TeamManagerAssert, TeamManager> {

  /**
   * Creates a new <code>{@link TeamManagerAssert}</code> to make assertions on actual TeamManager.
   * @param actual the TeamManager we want to make assertions on.
   */
  public TeamManagerAssert(TeamManager actual) {
    super(actual, TeamManagerAssert.class);
  }

  /**
   * factory method for TeamManager assertions.
   * @return a new <code>{@link TeamManagerAssert}</code>
   */
  public static TeamManagerAssert assertThat(TeamManager actual) {
    return new TeamManagerAssert(actual);
  }
}
