package org.assertj.examples.data.bug26;


/**
 * {@link WithGenericListType} specific assertions - Generated by me.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractWithGenericListTypeAssert} instead.
 */
public class WithGenericListTypeAssert extends AbstractWithGenericListTypeAssert<WithGenericListTypeAssert, WithGenericListType> {

  /**
   * Creates a new <code>{@link WithGenericListTypeAssert}</code> to make assertions on actual WithGenericListType.
   * @param actual the WithGenericListType we want to make assertions on.
   */
  public WithGenericListTypeAssert(WithGenericListType actual) {
    super(actual, WithGenericListTypeAssert.class);
  }

  /**
   * factory method for WithGenericListType assertions.
   * @return a new <code>{@link WithGenericListTypeAssert}</code>
   */
  public static WithGenericListTypeAssert assertThat(WithGenericListType actual) {
    return new WithGenericListTypeAssert(actual);
  }
}
