package java.nio.file;


/**
 * {@link Path} specific assertions - Generated by me.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractPathAssert} instead.
 */
public class PathAssert extends AbstractPathAssert<PathAssert, Path> {

  /**
   * Creates a new <code>{@link PathAssert}</code> to make assertions on actual Path.
   * @param actual the Path we want to make assertions on.
   */
  public PathAssert(Path actual) {
    super(actual, PathAssert.class);
  }

  /**
   * factory method for Path assertions.
   * @return a new <code>{@link PathAssert}</code>
   */
  public static PathAssert assertThat(Path actual) {
    return new PathAssert(actual);
  }
}
