package java.nio.file;


/**
 * {@link Path} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractPathAssert} instead.
 */
public class PathAssert extends AbstractPathAssert<PathAssert, Path> {

  /**
   * Creates a new <code>{@link PathAssert}</code> to make assertions on actual Path.
   * @param actual the Path we want to make assertions on.
   */
  public PathAssert(Path actual) {
    super(actual, PathAssert.class);
  }

  /**
   * An entry point for PathAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myPath)</code> and get specific assertion with code completion.
   * @param actual the Path we want to make assertions on.
   * @return a new <code>{@link PathAssert}</code>
   */
  public static PathAssert assertThat(Path actual) {
    return new PathAssert(actual);
  }
}
