/**
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 *
 * Copyright 2012-2013 the original author or authors.
 */
package org.assertj.examples.data.movie;

import static java.lang.String.format;

import org.assertj.core.api.AbstractAssert;
import org.assertj.core.api.Assertions;
import java.util.Date;


/**
 * {@link Movie} specific assertions - Generated by CustomAssertionGenerator.
 */
public class MovieAssert extends AbstractAssert<MovieAssert, Movie> {

  /**
   * Creates a new </code>{@link MovieAssert}</code> to make assertions on actual Movie.
   * @param actual the Movie we want to make assertions on.
   */
  public MovieAssert(Movie actual) {
    super(actual, MovieAssert.class);
  }

  /**
   * An entry point for MovieAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one's can write directly : <code>assertThat(myMovie)</code> and get specific assertion with code completion.
   * @param actual the Movie we want to make assertions on.
   * @return a new </code>{@link MovieAssert}</code>
   */
  public static MovieAssert assertThat(Movie actual) {
    return new MovieAssert(actual);
  }

  /**
   * Verifies that the actual Movie's releaseDate is equal to the given one.
   * @param releaseDate the given releaseDate to compare the actual Movie's releaseDate to.
   * @return this assertion object.
   * @throws AssertionError - if the actual Movie's releaseDate is not equal to the given one.
   */
  public MovieAssert hasReleaseDate(Date releaseDate) {
    // check that actual Movie we want to make assertions on is not null.
    isNotNull();

    // we overrides the default error message with a more explicit one
    String errorMessage = format("\nExpected <%s> releaseDate to be:\n  <%s>\n but was:\n  <%s>", actual, releaseDate, actual.getReleaseDate());
    
    // check
    if (!actual.getReleaseDate().equals(releaseDate)) { throw new AssertionError(errorMessage); }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual Movie's title is equal to the given one.
   * @param title the given title to compare the actual Movie's title to.
   * @return this assertion object.
   * @throws AssertionError - if the actual Movie's title is not equal to the given one.
   */
  public MovieAssert hasTitle(String title) {
    // check that actual Movie we want to make assertions on is not null.
    isNotNull();

    // we overrides the default error message with a more explicit one
    String errorMessage = format("\nExpected <%s> title to be:\n  <%s>\n but was:\n  <%s>", actual, title, actual.getTitle());
    
    // check
    if (!actual.getTitle().equals(title)) { throw new AssertionError(errorMessage); }

    // return the current assertion for method chaining
    return this;
  }

}
